# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y1eZuDJQ17qCvcqVPpxWmpHF7mNCTGh-
"""

import streamlit as st
import pickle
import numpy as np

# Load model
model = pickle.load(open("food_delivery_model.pkl", "rb"))

st.title("🚴 Food Delivery Time Predictor")

# Numeric inputs
distance = st.number_input("Distance (km)", 1.0, 50.0)
prep_time = st.number_input("Preparation Time (min)", 1.0, 60.0)
experience = st.number_input("Courier Experience (years)", 0.0, 20.0)
rating = st.number_input("Delivery Person Rating", 1.0, 5.0)

# Categorical inputs
weather = st.selectbox("Weather", ["Sunny", "Cloudy", "Rainy"])
traffic = st.selectbox("Traffic Level", ["Low", "Medium", "High"])
vehicle = st.selectbox("Vehicle Type", ["Bike", "Car"])
time_of_day = st.selectbox("Time of Day", ["Morning", "Afternoon", "Evening"])

# Label encoding (MUST match training)
weather_map = {"Sunny": 0, "Cloudy": 1, "Rainy": 2}
traffic_map = {"Low": 0, "Medium": 1, "High": 2}
vehicle_map = {"Bike": 0, "Car": 1}
time_map = {"Morning": 0, "Afternoon": 1, "Evening": 2}

# Input order MUST be same as X during training
input_data = np.array([[
    distance,
    prep_time,
    weather_map[weather],
    traffic_map[traffic],
    vehicle_map[vehicle],
    time_map[time_of_day],
    experience,
    rating
]])

if st.button("Predict Delivery Time"):
    prediction = model.predict(input_data)
    st.success(f"Estimated Delivery Time: {int(prediction[0])} minutes")