# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YMsPDZil0_cglBK0poDqBlMRB0FQkdOu
"""

import streamlit as st
import pickle
import numpy as np

# Load trained model
model = pickle.load(open("food_delivery_model.pkl", "rb"))

st.title("🚴 Food Delivery Time Predictor")

# Numeric input
distance = st.number_input("Distance (km)", 1, 20)

# Categorical inputs
weather = st.selectbox("Weather", ["Sunny", "Cloudy", "Rainy"])
traffic = st.selectbox("Traffic Level", ["Low", "Medium", "High"])
vehicle = st.selectbox("Vehicle Type", ["Bike", "Car"])

# Label encoding maps (MUST match training)
weather_map = {"Sunny": 0, "Cloudy": 1, "Rainy": 2}
traffic_map = {"Low": 0, "Medium": 1, "High": 2}
vehicle_map = {"Bike": 0, "Car": 1}

# Create input in SAME ORDER as training
input_data = np.array([[
    distance,
    weather_map[weather],
    traffic_map[traffic],
    vehicle_map[vehicle]
]])

# Prediction
if st.button("Predict Delivery Time"):
    prediction = model.predict(input_data)
    st.success(f"Estimated Delivery Time: {int(prediction[0])} minutes")